<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Categories' => 'Категория',
    'Category name: "{name}"' => 'Имя категории: "{name}"',
    'Go back' => 'Назад',
    'Home' => 'Главная',
    'List of news:' => 'Список новостей',
    'News' => 'Новости',
    'Online news' => 'Новости онлайн',
    'Start the journey' => 'Начать путишествие',
    'Subscribe to get the latest news' => 'Подпишитесь,чтобы получать последние обновления',
    'Tags' => 'Теги',
    'You are on Category/Index page' => 'Вы на странице категорий',
    'Tag name: "{name}"' => 'Имя тега: "{name}"',
    'You are on News/Index page' => 'Вы на странице новостей',
    'You are on Tag/Index page' => 'Вы на странице тегов',
];
